### ISSUE TITLE
Week 1 Proposal

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Bitcamp-Alexa#2]
Open a pull request to the master branch in the folder /week 1, adding a README.md to the root. 

This README.md should contain 

- [ ] Title of Project
- [ ] Description of Project
- [ ] Learning Outcomes
- [ ] List of Needed Technologies. (Twilio Account, Node.js, etc)
- [ ] Link to relevant resources

**Comment by kylebegovich** [comment]
Completed with pull request #5
